import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: '#000000',
	},
	header: {
		paddingHorizontal: 20,
		paddingTop: 16,
		paddingBottom: 6,
		gap: 4,
	},
	backButton: {
		alignSelf: 'flex-start',
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	backButtonText: {
		color: '#ffffff',
		fontSize: 11,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	headerActions: {
		marginTop: 10,
		alignItems: 'flex-start',
		gap: 8,
	},
	title: {
		color: '#ffffff',
		fontSize: 22,
		fontWeight: '700',
	},
	subtitle: {
		color: '#9aa0a6',
		fontSize: 13,
	},
	revenueCard: {
		marginHorizontal: 20,
		marginTop: 12,
		marginBottom: 8,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
	},
	socialCard: {
		marginHorizontal: 20,
		marginBottom: 8,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 10,
	},
	scheduleCard: {
		marginHorizontal: 20,
		marginBottom: 12,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 12,
	},
	scheduleHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	scheduleHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	scheduleTitle: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	scheduleToggle: {
		color: '#9aa0a6',
		fontSize: 16,
		fontWeight: '700',
	},
	scheduleSaveButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	scheduleSaveText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	scheduleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	scheduleDay: {
		width: 80,
		color: '#9aa0a6',
		fontSize: 13,
		textTransform: 'capitalize',
	},
	scheduleInput: {
		flex: 1,
backgroundColor: '#000',
		borderRadius: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		color: '#ffffff',
		paddingHorizontal: 10,
		paddingVertical: 8,
		fontSize: 13,
		minWidth: 70,
		textAlign: 'center',
	},
	scheduleInputWide: {
		flex: 1,
backgroundColor: '#000',
		borderRadius: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		color: '#ffffff',
		paddingHorizontal: 10,
		paddingVertical: 8,
		fontSize: 13,
	},
	scheduleDash: {
		color: '#9aa0a6',
		fontSize: 12,
		fontWeight: '700',
	},
	scheduleSection: {
		gap: 8,
	},
	scheduleSectionHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	scheduleSectionToggle: {
		color: '#9aa0a6',
		fontSize: 15,
		fontWeight: '700',
	},
	scheduleSubtitle: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '700',
	},
	scheduleInputRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	blockButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 10,
		paddingVertical: 10,
		paddingHorizontal: 14,
		alignItems: 'center',
	},
	blockButtonText: {
		color: '#00f0ff',
		fontSize: 13,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	blockTimeGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	blockTimeButton: {
		paddingVertical: 8,
		paddingHorizontal: 10,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
backgroundColor: '#000',
	},
	blockTimeButtonActive: {
		backgroundColor: '#00f0ff',
		borderColor: 'rgba(225, 6, 0, 0.85)',
	},
	blockTimeText: {
		color: '#ffffff',
		fontSize: 12,
		fontWeight: '600',
	},
	blockTimeTextActive: {
		color: '#000000',
	},
	scheduleAddButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 10,
		paddingHorizontal: 10,
		paddingVertical: 8,
	},
	scheduleAddText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	scheduleEmpty: {
		color: '#9aa0a6',
		fontSize: 12,
	},
	scheduleItemRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingVertical: 6,
	},
	scheduleItemText: {
		color: '#d1d5db',
		fontSize: 12,
	},
	scheduleRemoveText: {
		color: '#ff6b6b',
		fontSize: 11,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	reviewsCard: {
		marginHorizontal: 20,
		marginBottom: 12,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 12,
	},
	reviewsHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	reviewsTitle: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	reviewsSummary: {
		color: '#ffd700',
		fontSize: 13,
		fontWeight: '700',
	},
	reviewsLoading: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
	},
	reviewsLoadingText: {
		color: '#9aa0a6',
		fontSize: 13,
	},
	reviewsEmpty: {
		color: '#9aa0a6',
		fontSize: 13,
	},
	reviewRow: {
		backgroundColor: '#000',
		borderRadius: 12,
		padding: 12,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 8,
	},
	reviewHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	reviewName: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '700',
	},
	reviewDate: {
		color: '#9aa0a6',
		fontSize: 12,
	},
	reviewStars: {
		fontSize: 13,
	},
	reviewComment: {
		color: '#d1d5db',
		fontSize: 13,
		lineHeight: 18,
	},
	socialHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	paymentCard: {
		marginHorizontal: 20,
		marginBottom: 12,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 12,
	},
	paymentHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	paymentTitle: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	paymentEditButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	paymentEditText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	paymentForm: {
		gap: 10,
	},
	paymentInputLabel: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	paymentInput: {
backgroundColor: '#000',
		borderRadius: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		color: '#ffffff',
		paddingHorizontal: 12,
		paddingVertical: 10,
		fontSize: 14,
	},
	paymentSaveButton: {
		marginTop: 6,
		backgroundColor: '#00f0ff',
		borderRadius: 12,
		paddingVertical: 12,
		alignItems: 'center',
	},
	paymentSaveText: {
		color: '#000000',
		fontSize: 13,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	paymentRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 12,
	},
	paymentDetails: {
		flex: 1,
		gap: 4,
	},
	paymentLabel: {
		color: '#9aa0a6',
		fontSize: 13,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	paymentValue: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '600',
	},
	paymentButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	paymentButtonDisabled: {
		borderColor: 'rgba(225, 6, 0, 0.85)',
	},
	paymentButtonText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	qrContainer: {
		alignItems: 'center',
		paddingVertical: 8,
	},
	qrImage: {
		width: 220,
		height: 220,
		borderRadius: 12,
		backgroundColor: '#ffffff',
	},
	socialTitle: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	socialEditButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	socialEditText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	socialList: {
		gap: 6,
	},
	socialValue: {
		color: '#9aa0a6',
		fontSize: 13,
	},
	supportLinkText: {
		color: '#ffffff',
		fontSize: 13,
		paddingVertical: 2,
	},
	socialEmpty: {
		color: '#9aa0a6',
		fontSize: 13,
	},
	socialForm: {
		gap: 8,
	},
	socialLabel: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	socialInput: {
backgroundColor: '#000',
		borderRadius: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		color: '#ffffff',
		paddingHorizontal: 12,
		paddingVertical: 10,
		fontSize: 14,
	},
	socialSaveButton: {
		marginTop: 6,
		backgroundColor: '#00f0ff',
		borderRadius: 12,
		paddingVertical: 12,
		alignItems: 'center',
	},
	socialSaveText: {
		color: '#000000',
		fontSize: 13,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	sectionHeader: {
		paddingHorizontal: 20,
		paddingTop: 8,
		paddingBottom: 6,
	},
	dateRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginTop: 6,
	},
	dateLabel: {
		color: '#9aa0a6',
		fontSize: 12,
	},
	dateButton: {
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		borderRadius: 999,
		paddingHorizontal: 16,
		paddingVertical: 10,
	},
	dateButtonText: {
		color: '#00f0ff',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	historyButton: {
		alignSelf: 'flex-start',
		marginBottom: 2,
	},
	calendarCard: {
		marginHorizontal: 20,
		marginBottom: 8,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 10,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
	},
	sectionTitle: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	statusText: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	socialSpacer: {
		height: 12,
	},
	revenueLabel: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 1.2,
	},
	revenueValue: {
		color: '#00f0ff',
		fontSize: 22,
		fontWeight: '700',
		marginTop: 6,
	},
	revenueCount: {
		color: '#9aa0a6',
		fontSize: 12,
		marginTop: 4,
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	revenueLoading: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginTop: 6,
	},
	statsCard: {
		marginHorizontal: 20,
		marginBottom: 8,
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 10,
	},
	statsTitle: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	statsRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	statsLabel: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	statsValue: {
		color: '#ffffff',
		fontSize: 14,
		fontWeight: '700',
	},
	list: {
		paddingHorizontal: 20,
		paddingBottom: 24,
		gap: 12,
	},
	card: {
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 6,
	},
	dateText: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	timeText: {
		color: '#ffffff',
		fontSize: 13,
		fontWeight: '600',
	},
	timelineRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	timelineTime: {
		color: '#ffffff',
		fontSize: 18,
		fontWeight: '700',
		minWidth: 70,
	},
	timelineDetails: {
		flex: 1,
		gap: 2,
	},
	serviceText: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '600',
	},
	clientText: {
		color: '#9aa0a6',
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	priceText: {
		color: '#00f0ff',
		fontSize: 14,
		fontWeight: '700',
	},
	actionsRow: {
		flexDirection: 'row',
		gap: 10,
		marginTop: 8,
	},
	actionButton: {
		flex: 1,
		borderRadius: 10,
		paddingVertical: 10,
		alignItems: 'center',
	},
	primaryButton: {
		backgroundColor: '#00f0ff',
	},
	primaryButtonText: {
		color: '#000000',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	secondaryButton: {
		borderWidth: 1,
		borderColor: '#ff6b6b',
		backgroundColor: 'rgba(255,107,107,0.1)',
	},
	secondaryButtonText: {
		color: '#ff6b6b',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.6,
	},
	emptyText: {
		color: '#9aa0a6',
		fontSize: 13,
		textAlign: 'center',
		paddingTop: 30,
	},
	skeletonCard: {
backgroundColor: '#000',
		borderRadius: 14,
		padding: 16,
		borderWidth: 1,
		borderColor: 'rgba(225, 6, 0, 0.85)',
		gap: 10,
	},
	skeletonLineWide: {
		height: 18,
		backgroundColor: 'rgba(255,255,255,0.08)',
		borderRadius: 10,
		width: '70%',
	},
	skeletonLine: {
		height: 12,
		backgroundColor: 'rgba(255,255,255,0.08)',
		borderRadius: 10,
		width: '50%',
	},
	skeletonActions: {
		height: 32,
		backgroundColor: 'rgba(255,255,255,0.08)',
		borderRadius: 10,
		width: '100%',
		marginTop: 6,
	},
});
